### ISSUE TITLE
Website rather than pipsqeak 

### ISSUE THREAD

**Issue by T-om-X** [FuelRats/pipsqueak#140]
Report on the discord chanel of a commander not being able to access the irc client on the website. Commander Clapton reported it on the discord channel.

**Comment by Marenthyu** [comment]
Irrelevant to this repository. Closes #140

On Sun, Aug 21, 2016 at 11:59 AM +0200, "T-om-X" notifications@github.com wrote:

Report on the discord chanel of a commander not being able to access the irc client on the website. Commander Clapton reported it on the discord channel.

## 

You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/FuelRats/pipsqueak/issues/140
