### ISSUE TITLE
Accept empty commands if there's only one case

### ISSUE THREAD

**Issue by trezy** [FuelRats/pipsqueak#15]
Should commands like `!quote` require an identifier if there's only one case? I feel like that's unnecessary.

**Comment by tyrope** [comment]
For consistency sake I would not suggest coding in an edge-case like this, for two reasons:
- It introduces a point of failure in the code which requires very specific testing.
- It introduces a point of failure in human error when people don't realize there's more than 1 case.

However, I tend to leave feature requests up to user input for a while before shutting them down completely.

edit: ignore my label messing around below, it's not a feature it's a tweak to an existing feature.. It's late.

**Comment by trezy** [comment]
It'd be totally fair to skip the feature because it's not necessary which is why I added the discussion tag. However, it's more about user experience than anything. If there's only one case then it's logical to expect that it would respond with the info on that case. If there's more than one case then we send the same message we currently use when somebody uses a command without an identifier.

**Comment by duk3luk3** [comment]
I am in favour of this feature.

**Comment by dewiniaid** [comment]
I'm against this, mainly for the human-error reasons.  Also it raises questions like:
- What constitutes as a single case?  If there's only one active case but four inactive cases, what do we do?
- What happens when a new case comes in in the middle of doing a command on the single open case?

What could be potentially useful is remembering the most recent case a particular user interacted with, and defaulting commands to that case if they don't otherwise specify a case.  Typically you !quote a case before using !sub, for instance.  (Though in that case, there's some ambiguity of: If you !quote 1, is !sub 2 3 a request to delete line 3 of case 2, or replace line 2 of case 1 with "3"?)

**Comment by trezy** [comment]
@dewiniaid, both of your arguments against this are silly. 
1. A single case constitutes a single case. The status of those cases doesn't matter. 
2. IRC messages are synchronous. The bot should respond to these things based on responses from the API which will never be in an indefinite state. If the API indicates there's only one open case, quote it. If not, respond with a warning a list the number of cases.

**Comment by tyrope** [comment]
```
1. IRC messages are synchronous.
```

Network lag can shift messages in different order, or 2 users can send different messages at the exact same time... I've seen numerous times where IRC messages displayed in a different order on different computers (or even different clients on the same computer)

**Comment by dewiniaid** [comment]
I'm still against this, and here's a few (hopefully better) reasons:
1. Syntax for commands should be as uniform as reasonably possible.  If this behavior was expanded beyond `!quote` (to add that uniformity), it complicates parsing and adds ambiguity to other commands.  (If the only case is case 5, is `!inject 5 minutes on timer` adding "minutes on timer" to case 5 or "5 minutes on timer" to the only active case?  See also my earlier comments about `!sub`)
2. Requiring a case number reduces the chance and amount of accidental botspam in this hypothetical scenario:
   
   ```
   <Newrat> What's the command to see the comments on a case again?
   <Ratvet> !quote
   ```
   
   (A single line error message is better than the current !quote output)

As for IRC messages being synchronous: I'm fairly certain that IRC messages are mostly-synchronous, with two exceptions:
- Users connected to different servers may get messages sent on their server before messages sent by users on other servers due to latency added by the server-to-server transmission.
- Users see their own messages first because IRC servers don't echo messages back to their sender; IRC clients instead immediately add their own messages to the stream at effectively zero latency

**Comment by dewiniaid** [comment]
Closing for reasons indicated above.
