### ISSUE TITLE
Investigate feasibility of SOUNDEX instead of Levehnstein distance for !search

### ISSUE THREAD

**Issue by kenneaal** [FuelRats/pipsqueak#158]
Levehnstein is not really a good text search for the types of misspellings of system names we get. We might get better, more closely matching results from using SOUNDEX. Postgres should be able to natively support generating soundex from inserted records, so it might be worth looking into?

**Comment by Marenthyu** [comment]
As i am unaware of how either of these work, i would appreciate if you could look into what´needs to be changed - but if it is possible to put it in the same format as https://github.com/FuelRats/pipsqueak/blob/master/sopel-modules/rat-search.py#L75 it should be doable.

**Comment by Marenthyu** [comment]
I'm unsure of how to exactly do this in python with the tools we already have. May look into it in the future, but as it is not a high priority issue, i won't bother with it for now.

**Comment by Belserium** [comment]
From the nets: "Soundex algorithm was originally developed to aid in searching for Anglo-Saxon names in English. It's probably not the best choice these days."

Comes stock in postgres, but I have doubts that it would be any better than what Levehnstein already tells us, since Lev's is quite generic and not dependent on the corpus.

(However, this would be fun to test out: run the soundex for the known sector/system list and thus generate the soundex dictionary.)

Corpus specific method would require some data for the true system names and lots of mistypes. So, easier to go generic :)

**Comment by kenneaal** [comment]
We would'nt be doing a soundex on the entire sector name, just the PG name, like Alrai Sector. I've run some tests, and most misspellings of Alrai Sector returns the same soundex code. It bears further testing at least?

**Comment by Belserium** [comment]
Definately should be tested. Information scientist is just being sceptical on the result ;)
