### ISSUE TITLE
Change required permissions to !mdlist to registered user

### ISSUE THREAD

**Issue by SuperManifolds** [FuelRats/pipsqueak#171]
`<Delta_RC_2526> By the way, why is !mdlist for overseers and higher? I would think it would be useful for a rat to be able to go get the case ID from the list. !delete can remain overseer and higher, but I see no reason to block !mdlist. Accidental use of !md on active cases is somewhat common at the moment.`

**Comment by Marenthyu** [comment]
!mdlist is merely an alias for `!delete list` and thus, the permissions for it are tied to it. Also it is intentional as it polls the api every time it is used so it is to be used sparingly.
Also !mdadd (or !md) can ONLY be used on open cases. This is also intended as it a) lowers the required API Calls for the command to be executed  and b) it makes it a heck of a lot easier to implement and c) i see no need to restrict it to closed cases as most marked cases come from refreshes, which always create an open case and thus allowing open cases to be marked makes it easier to use as there is no need to first check the databasd id and then close it and then mark it.

**Comment by Marenthyu** [comment]
Also, !mdlist generates a lot of spam and requires a lot of time to fully finish execution (depending on the amount of marked cases) and this blocks the bot from responding to other commands (as is already known with !help) (fyi, this doesnt block rsignals as those are high priority. I should probably make ratmama_parse high priority as well.)

**Comment by Marenthyu** [comment]
Side note: even though !mdlist is an alias and tied to !delete's peemissions i can of course unlink them and change the permissions.

**Comment by SuperManifolds** [comment]
Your response has convinced me it is better as it is, disregard
