### ISSUE TITLE
PW link

### ISSUE THREAD

**Issue by CMDRAntarctica01** [FuelRats/pipsqueak#173]
Is it possible to make Mecha send the pw link in a pm to the targeted Rat ?

Update:
As I understand from PM's with Clapton, it already should do that, but the idea is about only sending a notification/message in #RC and send the link only in a PM

**Comment by UncleClapton** [comment]
it already does. :)

**Comment by CMDRAntarctica01** [comment]
Then why do I still see PW links in #RC  ?

**Comment by UncleClapton** [comment]
Assuming you're talking about !clear, It always sends a link to #RC under any circumstance.

**Comment by CMDRAntarctica01** [comment]
Ok, maybe I should've made myself a little more clear

**Comment by kenneaal** [comment]
Mecha sends the PW link to the rat that got the first limpet, as well as to #ratchat. The link to #ratchat is intentional, as it both keeps the mischief informed on case progress, and prevents case links from being lost in the void if the rat should have gone offline or otherwise no longer be reachable by the bot. (Such as a nickchange)
