### ISSUE TITLE
Add case-number in data-property in rescues

### ISSUE THREAD

**Issue by itssimple** [FuelRats/pipsqueak#177]

**Comment by Marenthyu** [comment]
@itssimple please provide an exact example how you want it, otherwise, I'll just add it as {"boardIndex":x, "markedForDeletion":{...}, ...}
Same for #176 which would go as {"status":{"FriendRequest":True/False, "WingRequest":True/False, "SysArrived":True/False, "BeaconSpotted":True/False, "InstanceSuccessful":True/False, "Fueled":True/False}} as to keep it the same as the Websocket messages.

**Comment by Marenthyu** [comment]
Seems to be working as intended, though im not sure if it updates correctly yet as i couldnt test it. Example Rescue element: {"id":"b1476b1e-199d-4b51-b42c-d73bd9cd1a72","active":true,"client":"NLK_64504","codeRed":false,"data":{"langID":"en","status":{"Fueled":false,"SysArrived":false,"WingRequest":false,"BeaconSpotted":false,"FriendRequest":false,"InstanceSuccessful":false},"IRCNick":"NLK_64504","boardIndex":1,"markedForDeletion":{"marked":false,"reason":"None.","reporter":"Noone."}},"open":true,"notes":"","platform":"pc","quotes":["Testcase Fuelum PC","[Autodetected system: Fuelum]"],"successful":true,"system":"Fuelum","title":null,"unidentifiedRats":[],"createdAt":"2016-09-29T15:46:53.357Z","updatedAt":"2016-09-29T15:46:53.848Z","rats":[],"epic":false,"firstLimpet":null}
