### ISSUE TITLE
Practice bot

### ISSUE THREAD

**Issue by Burwellian** [FuelRats/pipsqueak#60]
A second copy of the bot running in only a specific channel (E.G. #RatBot) independent from the main bot.

To allow Rats and Dispatchers to practice with the bot, learn commands, hands on without affecting live ops and impeding dispatch.

**Comment by dewiniaid** [comment]
Should be super-easy with the current iteration -- it wouldn't take much to break out the need for it to talk to the API at all, for instance.  It might not even require a separate bot since the bot can be aware of what channel it's on, but having a separate bot is better because of things like PMs.

I'd say kick the regular bot out of #DrillRats and use the practice bot in there -- that way dispatchers being drilled have access to the full suite of bot features and don't need to do 'fake' bot commands.

**Comment by dewiniaid** [comment]
Drillsqueak[BOT] is now live in #Drillrats and can also be used via PM
