### ISSUE TITLE
!assign command doubts

### ISSUE THREAD

**Issue by TheDivision** [FuelRats/pipsqueak#72]
Hey, I have my doubts about the assign command now it automatically suggests the client to send a friend request. Some rats have a underscore instead of a space, and clients might get confused about the part in brackets rats usually have behind their names. 

Imho, it also negates the human part of a dispatcher. They're humans, too! :man:

**Comment by SuperManifolds** [comment]
The bot will know the CMDR name of the rat in question and use that, this part has not been completed yet

**Comment by dewiniaid** [comment]
I think the concern here is more that the bot instructs clients to send a FR upon !assign, when that may not always be the best action to do.  Even once nick<->CMDR mapping is live, there may be occasions where we want to control when friending happens.

I may move the current behavior (perhaps with tweaked messaging) to a !assignfr command (or similar) and have a "assign only, no FR" version (like the original) where !assign is.

**Comment by TheDivision** [comment]
I think that is the best, indeed. It is sometimes necessary to use the 
!unassign command because of a rat signing out. I like the idea of a 
!assign command and a seperate !assignfr command.

**Comment by tyrope** [comment]
Interesting that this [requested](https://github.com/FuelRats/pipsqueak/issues/14) feature is now discussed to be removed/adjusted. I personally am of a neutral disposition to this (Either remove it, keep it, or the !assignfr/!gofr command)

CC: @trezy

**Comment by trezy** [comment]
I'd want to see a lot more dissent on this feature before removal. I was the one that originally made the request but I did so after a lot of deliberation with the tech team as well as the rest of the rats. If the rats as a whole disagree with the feature, so be it. As it stands, I don't think the dissent of one rat is worth removing it entirely.

Take a poll in #RatChat if you feel strongly about it. Otherwise it stays.

**Comment by dewiniaid** [comment]
TheDivision is not the first person to have complained about it -- just the
first person that actually opened an issue when I suggested people should
open an issue.

**Comment by trezy** [comment]
So, again, I want to see the results of a poll.

**Comment by T-om-X** [comment]
If we go with 2 commands can we make the one that's going to to be typed the most easy to type?

Personally i quite like the auto friend thing (can we have it when we wing too?) but I don't mind having to put somthing on like !assignf or !gof. When we get mapping it'll be much better but most clients should understand and you can always warn them anyway (e.g. for info Tom_X is Tom X in game)

**Comment by kenneaal** [comment]
There's really no need to code around this. It is edge case when it comes to an assignment not needing a FR instruction, and automating something around handling it is extraneous. Dispatch can simply say "Please ignore what Mecha said about friending them".

**Comment by T-om-X** [comment]
As mentioned last night when we had our first few real questions there are cases when you want to assign rats but are still not clear that whether the case is a code red or not in which case you want to keep the clients (clearly limited) cognitive bandwidth as narrow as possible on what you want them to do - introducing an extra 2 cognitive steps at this point is not going to help.  You could just instruct the rats to go without using the command but then they wont be logged on the case - one of the things I've found mecha most useful from a dispatching point of view is that if you have multiple cases coming at once you can afford not to concentrate too much on who you've sent where because you can interrogate the case in pm to find out who you've sent on it. I agree it's not often that it happens but it does happen. Just my 2p

**Comment by Marenthyu** [comment]
People are pretty much used to this by now (hi everyone btw that gets pinged by this message!) but the stripping implemented in 08454e5170261a13cf465d6f836ee1f255cc66fc pretty much fixes this partially as it removes any tags in the fr part. This at least removes the part a little, but i should move it to use the found rat's CMDR name anyway, if the rat got found. Will do in drillsqueak-newirc soon.
