### ISSUE TITLE
Everything in !list red after (CR)

### ISSUE THREAD

**Issue by Ozei** [FuelRats/pipsqueak#77]
![ratsqueakcrbug](https://cloud.githubusercontent.com/assets/19854378/15959270/a722b760-2f02-11e6-8338-702cddd41bca.PNG)

As you can see, everything after (CR) is in red in !list response.

Not the biggest or most urgent issue, but thought I would report it.

**Comment by blackrabt** [comment]
Could this be fixed at line 265 in rat-board.py by changing 
bot.reply('{0}\'s case ({1}):'.format(cmdr, plat))
to
bot.reply('{0}\'s case ({1}):'.format(cmdr, plat(color(colors.BLACK))))

That way it will always assign black text unless it is told otherwise, when sending the list to chat.

I haven't had a chance to test it out yet but it seems like it would work. - Second thought, I think it needs to be put at the head of that line.

**Comment by tyrope** [comment]
better fix would be to suffix the undo to the end of the CR tag, where the CR tag is created.

Tho I'm not sure what the sopel way of doing that off the top of my head, specific code I'm referring to is https://github.com/FuelRats/pipsqueak/blob/sopel-master/sopel-modules/rat-board.py#L330

**Comment by blackrabt** [comment]
Indeed. Good thinking sir. 

Guess it will be a bit of testing to see what does the job.

**Comment by blackrabt** [comment]
We tried to replicate the issue and could not. What IRC client and version are you using Ozei?

Issue is replicatable in irssi but not all IRC clients.

**Comment by Ozei** [comment]
I am using Irssi v. 0.8.15

I do realize that Irssi is wonky with colours, and that this issue is cosmetic and affects like 5 people...
